version: "3"
services:
  mysql:
    image: mysql
    container_name: first_sql
    tty: true
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      # - MYSQL_ROOT_PASSWORD=Student#0509
      - MYSQL_DATABASE=sai
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test#0509
      - MYSQL_ROOT_PASSWORD=Student#0509
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - django
    # command: sh -c 'mysql -u root -pStudent#0509 -e "create database sai";'
    # command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
  rest_api:
    build: .
    container_name: django1
    depends_on:
      - mysql
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # external_links:
    #   - first_sql
    links:
      - mysql:mysql
    ports:
      - 80:80
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    restart: unless-stopped
    networks:
      - django
    command: sh -c 'python manage.py migrate ; python manage.py runserver 0.0.0.0:80'

networks:
  django:
    driver: bridge
volumes:
  mysql-data:
