version: "3"
services:
  mysql:
    image: mysql
    container_name: first_sql
    ports:
      - 3306:3306
    environment:
      # - MYSQL_ROOT_PASSWORD=Student#0509
      - MYSQL_DATABASE=sai
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test#0509
      - MYSQL_ROOT_PASSWORD=Student#0509
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - django
  rest_api:
    build: .
    container_name: django1
    depends_on:
      - mysql
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # external_links:
    #   - first_sql
    # links:
    #   - mysql:mysql
    ports:
      - 80:80
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - django
    command: sh -c 'sleep 15 ; python manage.py makemigrations ; python manage.py migrate ; python manage.py runserver 0.0.0.0:80'

networks:
  django:
    driver: bridge
volumes:
  mysql-data:
